version: "3.9"

services:
  db:
    container_name: "${APP_NAME}_dev"
    image: postgres:15-alpine
    volumes:
      - storage_db:/var/lib/postgres/data
    ports:
      - ${PG_PORT}:5432
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB_NAME}

volumes:
  storage_db:
